USE ROLE SECURITYADMIN;

-- Functional Roles Creation
CREATE ROLE IF NOT EXISTS MH_INGEST_FR_ROLE
COMMENT = 'Role for data ingestion services.';

CREATE ROLE IF NOT EXISTS MH_DATA_ENGINEER_FR_ROLE
COMMENT = 'Role for data engineers building transformation pipelines.';

CREATE ROLE IF NOT EXISTS MH_DATA_ANALYST_FR_ROLE
COMMENT = 'Role for data analysts, BI tools, and reporting.';

-- Access Roles Creation
CREATE ROLE IF NOT EXISTS MH_INGEST_RW
COMMENT = 'Grants comprehensive read/write access for ingesting data.';

CREATE ROLE IF NOT EXISTS MH_DATA_ENGINEER_RW
COMMENT = 'Grants comprehensive read/write access for transforming data.';

CREATE ROLE IF NOT EXISTS MH_DATA_ANALYST_RO
COMMENT = 'Grants comprehensive read access for data analysis.';



-- DATABASE LEVEL GRANTS

USE DATABASE MH_DB;

-- Database usage for all roles
GRANT USAGE ON DATABASE MH_DB TO ROLE MH_INGEST_RW;
GRANT USAGE ON DATABASE MH_DB TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON DATABASE MH_DB TO ROLE MH_DATA_ANALYST_RO;



-- RAW SCHEMA GRANTS


-- DATA INGEST ROLE
GRANT USAGE ON SCHEMA MH_RAW TO ROLE MH_INGEST_RW;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE, CREATE STREAM, CREATE TASK 
ON SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;

-- Grants on existing objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON ALL TABLES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;

-- Grants on future objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON FUTURE TABLES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_INGEST_RW;


-- DATA ENGINEER ROLE
GRANT USAGE ON SCHEMA MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT, CREATE STAGE, 
CREATE PIPE, CREATE STREAM, CREATE TASK 
ON SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;

-- Grants on existing objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON ALL TABLES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;

-- Grants on future objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON FUTURE TABLES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ENGINEER_RW;


-- DATA ANALYST ROLE
GRANT USAGE ON SCHEMA MH_RAW TO ROLE MH_DATA_ANALYST_RO;

-- Grants on existing objects
GRANT SELECT ON ALL TABLES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;

-- Grants on future objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_RAW TO ROLE MH_DATA_ANALYST_RO;



-- HARMONIZED SCHEMA GRANTS


-- DATA INGEST ROLE
GRANT USAGE ON SCHEMA MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE, CREATE STREAM, CREATE TASK 
ON SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;

-- Grants on existing objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON ALL TABLES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;

-- Grants on future objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON FUTURE TABLES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_INGEST_RW;


-- DATA ENGINEER ROLE
GRANT USAGE ON SCHEMA MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT, CREATE STAGE, 
CREATE PIPE, CREATE STREAM, CREATE TASK 
ON SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;

-- Grants on existing objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON ALL TABLES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;

-- Grants on future objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON FUTURE TABLES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ENGINEER_RW;


-- DATA ANALYST ROLE
GRANT USAGE ON SCHEMA MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;

-- Grants on existing objects
GRANT SELECT ON ALL TABLES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;

-- Grants on future objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_HARMONIZED TO ROLE MH_DATA_ANALYST_RO;



-- CONSUMPTION SCHEMA GRANTS


-- DATA INGEST ROLE
GRANT USAGE ON SCHEMA MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE, CREATE STREAM, CREATE TASK 
ON SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;

-- Grants on existing objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON ALL TABLES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;

-- Grants on future objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON FUTURE TABLES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_INGEST_RW;


-- DATA ENGINEER ROLE
GRANT USAGE ON SCHEMA MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW, 
CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT, CREATE STAGE, 
CREATE PIPE, CREATE STREAM, CREATE TASK 
ON SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;

-- Grants on existing objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON ALL TABLES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;

-- Grants on future objects
GRANT SELECT, INSERT, TRUNCATE, DELETE, REFERENCES, UPDATE ON FUTURE TABLES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ENGINEER_RW;


-- DATA ANALYST ROLE
GRANT USAGE ON SCHEMA MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;

-- Grants on existing objects
GRANT SELECT ON ALL TABLES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;
GRANT SELECT ON ALL VIEWS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;

-- Grants on future objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA MH_DB.MH_CONSUMPTION TO ROLE MH_DATA_ANALYST_RO;



-- ROLE HIERARCHY

USE ROLE SECURITYADMIN;

-- Grant access roles to functional roles
GRANT ROLE MH_INGEST_RW TO ROLE MH_INGEST_FR_ROLE;
GRANT ROLE MH_DATA_ENGINEER_RW TO ROLE MH_DATA_ENGINEER_FR_ROLE;
GRANT ROLE MH_DATA_ANALYST_RO TO ROLE MH_DATA_ANALYST_FR_ROLE;

-- Grant functional roles to SYSADMIN role
GRANT ROLE MH_INGEST_FR_ROLE TO ROLE SYSADMIN;
GRANT ROLE MH_DATA_ANALYST_FR_ROLE TO ROLE SYSADMIN;
GRANT ROLE MH_DATA_ENGINEER_FR_ROLE TO ROLE SYSADMIN;



-- WAREHOUSE GRANTS


-- Ownership grants
GRANT OWNERSHIP ON WAREHOUSE MH_ELT_WH TO ROLE SYSADMIN;
GRANT OWNERSHIP ON WAREHOUSE MH_ANALYST_WH TO ROLE SYSADMIN;

-- Usage grants
GRANT USAGE ON WAREHOUSE MH_ELT_WH TO ROLE MH_INGEST_FR_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE MH_ELT_WH TO ROLE MH_DATA_ENGINEER_FR_ROLE;
GRANT USAGE ON WAREHOUSE MH_ANALYST_WH TO ROLE MH_DATA_ANALYST_FR_ROLE;



-- USER GRANTS

-- Ingest functional role
GRANT ROLE MH_INGEST_FR_ROLE TO USER DEV_SHARMA;
GRANT ROLE MH_INGEST_FR_ROLE TO USER ADITYA;
GRANT ROLE MH_INGEST_FR_ROLE TO USER DEVANSH_NEW;
GRANT ROLE MH_INGEST_FR_ROLE TO USER UNIKA;
-- Analyst functional role
GRANT ROLE MH_DATA_ANALYST_FR_ROLE TO USER SONAM;
GRANT ROLE MH_DATA_ANALYST_FR_ROLE TO USER ANIKET;
-- Engineer functional role
GRANT ROLE MH_DATA_ENGINEER_FR_ROLE TO USER DEV_SHARMA;
GRANT ROLE MH_DATA_ENGINEER_FR_ROLE TO USER ADITYA;
GRANT ROLE MH_DATA_ENGINEER_FR_ROLE TO USER DEVANSH_NEW;
GRANT ROLE MH_DATA_ENGINEER_FR_ROLE TO USER UNIKA;