
CREATE OR REPLACE PROCEDURE MH_PERFORMANCE_TEST.SYNTHETIC_LAB.generating_1m_rows()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN


CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.SYNTHETIC_LAB.TEMP_SURVEY_AUGMENTED_1M AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY NULL) AS SURVEY_ID,
    s.* EXCLUDE SURVEY_ID
FROM MH_DEV_DB.MH_RAW.SURVEY_AUGMENTED s
CROSS JOIN MULTIPLIER_NUMBERS m
LIMIT 1000000; 


CREATE OR REPLACE TABLE TEMP_PATIENT_HISTORY_1M AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY NULL) AS HISTORY_ID, -- Clean ID: 1, 2, 3...
    MOD(ROW_NUMBER() OVER (ORDER BY NULL) - 1, 1000000) + 1 AS SURVEY_ID, -- Links to Survey 1..1M
    h.DIAGNOSIS_DATE, h.DIAGNOSIS, h.TREATMENT_TYPE, h.MEDICATION, 
    h.TREATMENT_DURATION_MONTHS, h.SESSIONS_COMPLETED, h.IMPROVEMENT_SCORE, 
    h.CURRENT_STATUS, h.INSURANCE_COVERAGE
FROM MH_DEV_DB.MH_RAW.PATIENT_HISTORY h
CROSS JOIN MULTIPLIER_NUMBERS m
LIMIT 1200000; -- Exact count


CREATE OR REPLACE TABLE TEMP_TREATMENTS_OUTCOMES_1M AS
SELECT 
    ROW_NUMBER() OVER (ORDER BY NULL) AS OUTCOME_ID,
    ROW_NUMBER() OVER (ORDER BY NULL) AS HISTORY_ID, -- Matches History ID 1..1.2M perfectly
    MOD(ROW_NUMBER() OVER (ORDER BY NULL) - 1, 1000000) + 1 AS SURVEY_ID, -- Matches Survey ID Logic
    t.FOLLOW_UP_DATE, t.PHQ9_SCORE, t.GAD7_SCORE, t.WORK_PRODUCTIVITY_SCORE, 
    t.LIFE_SATISFACTION_SCORE, t.THERAPY_ATTENDANCE_RATE, t.MEDICATION_ADHERENCE, 
    t.SYMPTOM_SEVERITY, t.RECOMMEND_TREATMENT
FROM MH_DEV_DB.MH_RAW.TREATMENTS_OUTCOMES t
CROSS JOIN MULTIPLIER_NUMBERS m
LIMIT 1200000; -- Exact count


-- Demographics
CREATE OR REPLACE TABLE TEMP_DEMOGRAPHIC_EXTENDED_1M AS
SELECT ROW_NUMBER() OVER (ORDER BY NULL) AS SURVEY_ID, d.* EXCLUDE SURVEY_ID
FROM MH_DEV_DB.MH_RAW.DEMOGRAPHIC_EXTENTED d CROSS JOIN MULTIPLIER_NUMBERS m LIMIT 1000000;

-- Responses
CREATE OR REPLACE TABLE TEMP_SURVEY_RESPONCE_DETAILS_1M AS
SELECT ROW_NUMBER() OVER (ORDER BY NULL) AS SURVEY_ID, r.* EXCLUDE SURVEY_ID
FROM MH_DEV_DB.MH_RAW.SURVEY_RESPONCE_DETAILS r CROSS JOIN MULTIPLIER_NUMBERS m LIMIT 1000000;

-- Mappings
CREATE OR REPLACE TABLE TEMP_MAPPINGS_1M AS
SELECT ROW_NUMBER() OVER (ORDER BY NULL) AS SURVEY_ID, map.* EXCLUDE SURVEY_ID
FROM MH_DEV_DB.MH_RAW.SURVEY_COMPNAY_MAPPINGS map CROSS JOIN MULTIPLIER_NUMBERS m LIMIT 1000000;

  RETURN ''Success: All tables truncated and data loaded.'';
END;';