CREATE OR REPLACE PROCEDURE MH_PERFORMANCE_TEST.MH_HARMONIZED.SP_DATA_MODEL()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    -- 1. Create Dim_Date
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Date;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Date (
        DateKey NUMBER(8) PRIMARY KEY,
        FullDate DATE,
        Year NUMBER,
        Quarter NUMBER,
        Month NUMBER,
        MonthName VARCHAR
    );

    INSERT INTO MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Date
    SELECT TO_NUMBER(TO_VARCHAR(d, ''YYYYMMDD'')) DateKey,
           d FullDate,
           YEAR(d) Year,
           QUARTER(d) Quarter,
           MONTH(d) Month,
           MONTHNAME(d) MonthName
    FROM (SELECT DATEADD(day, seq4(), ''2020-01-01'') d
          FROM TABLE(GENERATOR(ROWCOUNT => 3650)));
        
    -- 2. Create Dim_Company 
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Company;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Company (
        COMPANY_ID NUMBER(38,0) PRIMARY KEY,
        COMPANY_NAME VARCHAR,
        TECH_COMPANY BOOLEAN,
        EMPLOYEE_COUNT_RANGE VARCHAR,
        REMOTE_WORK_POLICY BOOLEAN,
        MENTAL_HEALTH_BENEFITS BOOLEAN,
        WELLNESS_PROGRAM_AVAILABLE BOOLEAN,
        EAP_PROGRAM BOOLEAN,
        MENTAL_HEALTH_COVERAGE_PCT NUMBER(38,16),
        SICK_LEAVE_DAYS VARCHAR,
        FLEXIBLE_HOURS BOOLEAN,
        MENTAL_HEALTH_TRAINING BOOLEAN,
        STIGMA_REDUCTION_PROGRAMS BOOLEAN
    );
    INSERT INTO MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Company
    SELECT COMPANY_ID, COMPANY_NAME, TECH_COMPANY, EMPLOYEE_COUNT_RANGE, 
           REMOTE_WORK_POLICY, MENTAL_HEALTH_BENEFITS, WELLNESS_PROGRAM_AVAILABLE,
           EAP_PROGRAM, MENTAL_HEALTH_COVERAGE_PCT, SICK_LEAVE_DAYS,
           FLEXIBLE_HOURS, MENTAL_HEALTH_TRAINING, STIGMA_REDUCTION_PROGRAMS
    FROM MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_WORKPLACE_DETAILS;

    -- 3. Create Dim_Respondent
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Respondent;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Respondent (
        SURVEY_ID NUMBER(38,0) PRIMARY KEY,
        TIMESTAMP TIMESTAMP_NTZ(9),
        AGE NUMBER(38,0),
        GENDER VARCHAR,
        COUNTRY VARCHAR,
        STATE VARCHAR,
        SELF_EMPLOYED BOOLEAN,
        FAMILY_HISTORY BOOLEAN,
        TREATMENT BOOLEAN,
        WORK_INTERFERE VARCHAR,
        NO_EMPLOYEES VARCHAR,
        REMOTE_WORK BOOLEAN,
        TECH_COMPANY BOOLEAN,
        BENEFITS VARCHAR,
        CARE_OPTIONS VARCHAR,
        WELLNESS_PROGRAM VARCHAR,
        SEEK_HELP VARCHAR,
        ANONYMITY VARCHAR,
        LEAVE VARCHAR,
        MENTAL_HEALTH_CONSEQUENCE VARCHAR,
        PHYS_HEALTH_CONSEQUENCE VARCHAR,
        COWORKERS VARCHAR,
        SUPERVISOR VARCHAR,
        MENTAL_HEALTH_INTERVIEW VARCHAR,
        PHYS_HEALTH_INTERVIEW VARCHAR,
        MENTAL_VS_PHYSICAL VARCHAR,
        OBS_CONSEQUENCE BOOLEAN,
        INCOME_LEVEL VARCHAR,
        EDUCATION_LEVEL VARCHAR,
        MARITAL_STATUS VARCHAR,
        EMPLOYMENT_STATUS VARCHAR,
        YEARS_IN_FIELD NUMBER(38,0),
        HOUSEHOLD_SIZE NUMBER(38,0),
        HAS_CHILDREN BOOLEAN,
        URBAN_RURAL VARCHAR,
        HEALTH_INSURANCE_TYPE VARCHAR,
        STIGMA_PERCEPTION_SCORE NUMBER(38,0),
        SUPPORT_NETWORK_SCORE NUMBER(38,0),
        TREATMENT_BARRIER_SCORE NUMBER(38,0),
        WORK_IMPACT_SEVERITY NUMBER(38,0),
        BENEFITS_AWARENESS NUMBER(38,0),
        ANONYMITY_CONCERN NUMBER(38,0),
        LEAVE_DIFFICULTY NUMBER(38,0)
    );
    INSERT INTO MH_PERFORMANCE_TEST.MH_HARMONIZED.Dim_Respondent
    SELECT aug.SURVEY_ID, aug.TIMESTAMP, aug.AGE, aug.GENDER, aug.COUNTRY, aug.STATE,
           aug.SELF_EMPLOYED, aug.FAMILY_HISTORY, aug.TREATMENT, aug.WORK_INTERFERE,
           aug.NO_EMPLOYEES, aug.REMOTE_WORK, aug.TECH_COMPANY, aug.BENEFITS,
           aug.CARE_OPTIONS, aug.WELLNESS_PROGRAM, aug.SEEK_HELP, aug.ANONYMITY,
           aug.LEAVE, aug.MENTAL_HEALTH_CONSEQUENCE, aug.PHYS_HEALTH_CONSEQUENCE,
           aug.COWORKERS, aug.SUPERVISOR, aug.MENTAL_HEALTH_INTERVIEW,
           aug.PHYS_HEALTH_INTERVIEW, aug.MENTAL_VS_PHYSICAL, aug.OBS_CONSEQUENCE,
           dem.INCOME_LEVEL, dem.EDUCATION_LEVEL, dem.MARITAL_STATUS,
           dem.EMPLOYMENT_STATUS, dem.YEARS_IN_FIELD, dem.HOUSEHOLD_SIZE,
           dem.HAS_CHILDREN, dem.URBAN_RURAL, dem.HEALTH_INSURANCE_TYPE,
           resp.STIGMA_PERCEPTION_SCORE, resp.SUPPORT_NETWORK_SCORE,
           resp.TREATMENT_BARRIER_SCORE, resp.WORK_IMPACT_SEVERITY,
           resp.BENEFITS_AWARENESS, resp.ANONYMITY_CONCERN, resp.LEAVE_DIFFICULTY
    FROM MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_AUGMENTED aug
    LEFT JOIN MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_DEMOGRAPHIC_EXTENTED dem ON aug.SURVEY_ID = dem.SURVEY_ID
    LEFT JOIN MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_RESPONCE_DETAILS resp ON aug.SURVEY_ID = resp.SURVEY_ID;

    -- 4. Create Dim_Treatment_History
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.DIM_TREATMENT_HISTORY;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.DIM_TREATMENT_HISTORY (
        TREATMENT_HISTORY_KEY NUMBER(38,0) IDENTITY(1,1) PRIMARY KEY,
        DIAGNOSIS VARCHAR,
        TREATMENT_TYPE VARCHAR,
        MEDICATION VARCHAR,
        CURRENT_STATUS VARCHAR,
        INSURANCE_COVERAGE VARCHAR
    );
    INSERT INTO MH_PERFORMANCE_TEST.MH_HARMONIZED.DIM_TREATMENT_HISTORY (DIAGNOSIS, TREATMENT_TYPE, MEDICATION, CURRENT_STATUS, INSURANCE_COVERAGE)
    SELECT DISTINCT DIAGNOSIS, TREATMENT_TYPE, MEDICATION, CURRENT_STATUS, INSURANCE_COVERAGE
    FROM MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_PATIENT_HISTORY;

    -- 5. Create Fact_Treatment_Outcomes (last - depends on other dims)
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.FACT_TREATMENT_OUTCOMES;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.FACT_TREATMENT_OUTCOMES (
        OUTCOME_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
        HISTORY_ID NUMBER(38,0),
        SURVEY_ID NUMBER(38,0),
        COMPANY_ID NUMBER(38,0),
        TREATMENTHISTORYKEY NUMBER(38,0),
        FOLLOWUPDATEKEY NUMBER(8,0),
        DIAGNOSISDATEKEY NUMBER(8,0),
        PHQ9_SCORE NUMBER(38,1),
        GAD7_SCORE NUMBER(38,1),
        WORK_PRODUCTIVITY_SCORE NUMBER(38,1),
        LIFE_SATISFACTION_SCORE NUMBER(38,1),
        MEDICATION_ADHERENCE VARCHAR,
        SYMPTOM_SEVERITY VARCHAR,
        RECOMMEND_TREATMENT VARCHAR,
        THERAPY_ATTENDANCE_RATE NUMBER(38,1),
        TREATMENT_DURATION_MONTHS NUMBER(38,1),
        SESSIONS_COMPLETED NUMBER(38,0),
        IMPROVEMENT_SCORE NUMBER(38,1)
    );
    INSERT INTO MH_PERFORMANCE_TEST.MH_HARMONIZED.FACT_TREATMENT_OUTCOMES
    SELECT t.OUTCOME_ID, t.HISTORY_ID, ph.SURVEY_ID, scm.COMPANY_ID,
           dth.TREATMENT_HISTORY_KEY,
           COALESCE(TO_NUMBER(TO_CHAR(t.FOLLOW_UP_DATE, ''YYYYMMDD'')), 0),
           COALESCE(TO_NUMBER(TO_CHAR(ph.DIAGNOSIS_DATE, ''YYYYMMDD'')), 0),
           t.PHQ9_SCORE, t.GAD7_SCORE, t.WORK_PRODUCTIVITY_SCORE, t.LIFE_SATISFACTION_SCORE,
           t.MEDICATION_ADHERENCE, t.SYMPTOM_SEVERITY, t.RECOMMEND_TREATMENT,
           t.THERAPY_ATTENDANCE_RATE, ph.TREATMENT_DURATION_MONTHS,
           ph.SESSIONS_COMPLETED, ph.IMPROVEMENT_SCORE
    FROM MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_TREATMENTS_OUTCOMES t
    JOIN MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_PATIENT_HISTORY ph ON t.HISTORY_ID = ph.HISTORY_ID
    LEFT JOIN MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_COMPANY_MAPPINGS scm ON ph.SURVEY_ID = scm.SURVEY_ID
    LEFT JOIN MH_PERFORMANCE_TEST.MH_HARMONIZED.DIM_TREATMENT_HISTORY dth ON ph.DIAGNOSIS = dth.DIAGNOSIS
        AND ph.TREATMENT_TYPE = dth.TREATMENT_TYPE
        AND ph.MEDICATION = dth.MEDICATION
        AND ph.CURRENT_STATUS = dth.CURRENT_STATUS
        AND ph.INSURANCE_COVERAGE = dth.INSURANCE_COVERAGE;
    RETURN ''SUCCESS: Dimensional model built - 5 tables created & populated'';
EXCEPTION
    WHEN OTHER THEN
        RETURN ''ERROR: '' || SQLERRM;
END;
';