CREATE OR REPLACE PROCEDURE MH_PERFORMANCE_TEST.MH_HARMONIZED.SP_LOAD_HARMONIZED()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    -- 1. HARM_SURVEY_AUGMENTED
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_AUGMENTED;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_AUGMENTED AS
    SELECT
        SURVEY_ID,
        "TIMESTAMP",
        CASE WHEN AGE <= 16 OR AGE > 100 THEN NULL ELSE AGE END AS AGE,
        CASE
            WHEN LOWER(TRIM(GENDER)) IN (''male'', ''mail'', ''maile'', ''mal'', ''malr'', ''mslr'', ''msle'', ''m'', ''ma'', ''cis male'', ''cis man'', ''male (cis)'', ''guy (-ish) ^_^'', ''man'') THEN ''Male''
            WHEN LOWER(TRIM(GENDER)) IN (''female'', ''femail'', ''femak'', ''femake'', ''f'', ''woman'', ''cis female'', ''female (cis)'', ''cis-female/femme'') THEN ''Female''
            WHEN LOWER(TRIM(GENDER)) LIKE ''%trans%'' AND LOWER(TRIM(GENDER)) LIKE ''%female%'' THEN ''Trans Female''
            WHEN LOWER(TRIM(GENDER)) IN (''non-binary'', ''enby'', ''genderqueer'', ''androgyne'') THEN ''Non-Binary''
            WHEN LOWER(TRIM(GENDER)) = ''fluid'' THEN ''Gender Fluid''
            ELSE ''Other''
        END AS GENDER,
        COALESCE(UPPER(TRIM(COUNTRY)), ''NA'') AS COUNTRY,
        COALESCE(UPPER(TRIM(STATE)), ''Unknown'') AS STATE,
        COALESCE(SELF_EMPLOYED, FALSE) AS SELF_EMPLOYED,
        COALESCE(FAMILY_HISTORY, FALSE) AS FAMILY_HISTORY,
        COALESCE(TREATMENT, FALSE) AS TREATMENT,
        COALESCE(NULLIF(TRIM(WORK_INTERFERE), ''''), ''NA'') AS WORK_INTERFERE,
        COALESCE(NULLIF(TRIM(NO_EMPLOYEES), ''''), ''NA'') AS NO_EMPLOYEES,
        COALESCE(REMOTE_WORK, FALSE) AS REMOTE_WORK,
        COALESCE(TECH_COMPANY, FALSE) AS TECH_COMPANY,
        COALESCE(NULLIF(TRIM(BENEFITS), ''''), ''NA'') AS BENEFITS,
        COALESCE(NULLIF(TRIM(CARE_OPTIONS), ''''), ''NA'') AS CARE_OPTIONS,
        COALESCE(NULLIF(TRIM(WELLNESS_PROGRAM), ''''), ''NA'') AS WELLNESS_PROGRAM,
        COALESCE(NULLIF(TRIM(SEEK_HELP), ''''), ''NA'') AS SEEK_HELP,
        COALESCE(NULLIF(TRIM(ANONYMITY), ''''), ''NA'') AS ANONYMITY,
        COALESCE(NULLIF(TRIM(LEAVE), ''''), ''NA'') AS LEAVE,
        COALESCE(NULLIF(TRIM(MENTAL_HEALTH_CONSEQUENCE), ''''), ''NA'') AS MENTAL_HEALTH_CONSEQUENCE,
        COALESCE(NULLIF(TRIM(PHYS_HEALTH_CONSEQUENCE), ''''), ''NA'') AS PHYS_HEALTH_CONSEQUENCE,
        COALESCE(NULLIF(TRIM(COWORKERS), ''''), ''NA'') AS COWORKERS,
        COALESCE(NULLIF(TRIM(SUPERVISOR), ''''), ''NA'') AS SUPERVISOR,
        COALESCE(NULLIF(TRIM(MENTAL_HEALTH_INTERVIEW), ''''), ''NA'') AS MENTAL_HEALTH_INTERVIEW,
        COALESCE(NULLIF(TRIM(PHYS_HEALTH_INTERVIEW), ''''), ''NA'') AS PHYS_HEALTH_INTERVIEW,
        COALESCE(NULLIF(TRIM(MENTAL_VS_PHYSICAL), ''''), ''NA'') AS MENTAL_VS_PHYSICAL,
        COALESCE(OBS_CONSEQUENCE, FALSE) AS OBS_CONSEQUENCE,
        CASE WHEN COMMENTS IS NULL OR TRIM(COMMENTS) = '''' THEN ''NA''
             WHEN REGEXP_SUBSTR(COMMENTS, ''^[A-Za-z]'') IS NULL THEN COALESCE(REGEXP_SUBSTR(COMMENTS, ''[A-Za-z].*''), ''NA'')
             ELSE TRIM(COMMENTS)
        END AS COMMENTS
    FROM MH_PERFORMANCE_TEST.MH_RAW.SURVEY_AUGMENTED;   -- ← Fixed schema


    -- 2. HARM_DEMOGRAPHIC_EXTENTED
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_DEMOGRAPHIC_EXTENTED;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_DEMOGRAPHIC_EXTENTED AS
    SELECT SURVEY_ID,
           COALESCE(NULLIF(TRIM(INCOME_LEVEL), ''''), ''Unknown'') AS INCOME_LEVEL,
           COALESCE(NULLIF(TRIM(EDUCATION_LEVEL), ''''), ''Unknown'') AS EDUCATION_LEVEL,
           COALESCE(NULLIF(TRIM(MARITAL_STATUS), ''''), ''Unknown'') AS MARITAL_STATUS,
           COALESCE(NULLIF(TRIM(EMPLOYMENT_STATUS), ''''), ''Unknown'') AS EMPLOYMENT_STATUS,
           COALESCE(YEARS_IN_FIELD, 0) AS YEARS_IN_FIELD,
           COALESCE(HOUSEHOLD_SIZE, 0) AS HOUSEHOLD_SIZE,
           COALESCE(HAS_CHILDREN, FALSE) AS HAS_CHILDREN,
           COALESCE(NULLIF(TRIM(URBAN_RURAL), ''''), ''Unknown'') AS URBAN_RURAL,
           COALESCE(NULLIF(TRIM(HEALTH_INSURANCE_TYPE), ''''), ''Unknown'') AS HEALTH_INSURANCE_TYPE
    FROM MH_PERFORMANCE_TEST.MH_RAW.DEMOGRAPHIC_EXTENTED;   -- ← Fixed


    -- 3. HARM_SURVEY_RESPONCE_DETAILS
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_RESPONCE_DETAILS;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_RESPONCE_DETAILS AS
    SELECT SURVEY_ID,
           COALESCE(STIGMA_PERCEPTION_SCORE, 0) AS STIGMA_PERCEPTION_SCORE,
           COALESCE(SUPPORT_NETWORK_SCORE, 0) AS SUPPORT_NETWORK_SCORE,
           COALESCE(TREATMENT_BARRIER_SCORE, 0) AS TREATMENT_BARRIER_SCORE,
           COALESCE(WORK_IMPACT_SEVERITY, 0) AS WORK_IMPACT_SEVERITY,
           COALESCE(BENEFITS_AWARENESS, 0) AS BENEFITS_AWARENESS,
           COALESCE(ANONYMITY_CONCERN, 0) AS ANONYMITY_CONCERN,
           COALESCE(LEAVE_DIFFICULTY, 0) AS LEAVE_DIFFICULTY
    FROM MH_PERFORMANCE_TEST.MH_RAW.SURVEY_RESPONCE_DETAILS;   -- ← Fixed


    -- 4. HARM_PATIENT_HISTORY
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_PATIENT_HISTORY;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_PATIENT_HISTORY AS
    SELECT HISTORY_ID, SURVEY_ID,
           COALESCE(NULLIF(TRIM(DIAGNOSIS), ''''), ''Unknown'') AS DIAGNOSIS,
           DIAGNOSIS_DATE,
           COALESCE(NULLIF(TRIM(TREATMENT_TYPE), ''''), ''Unknown'') AS TREATMENT_TYPE,
           COALESCE(NULLIF(TRIM(MEDICATION), ''''), ''None'') AS MEDICATION,
           COALESCE(TREATMENT_DURATION_MONTHS, 0) AS TREATMENT_DURATION_MONTHS,
           COALESCE(SESSIONS_COMPLETED, 0) AS SESSIONS_COMPLETED,
           COALESCE(IMPROVEMENT_SCORE, 0) AS IMPROVEMENT_SCORE,
           COALESCE(NULLIF(TRIM(CURRENT_STATUS), ''''), ''Unknown'') AS CURRENT_STATUS,
           COALESCE(NULLIF(TRIM(INSURANCE_COVERAGE), ''''), ''Unknown'') AS INSURANCE_COVERAGE
    FROM MH_PERFORMANCE_TEST.MH_RAW.PATIENT_HISTORY;   -- ← Fixed


    -- 5. HARM_TREATMENTS_OUTCOMES
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_TREATMENTS_OUTCOMES;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_TREATMENTS_OUTCOMES AS
    SELECT OUTCOME_ID, HISTORY_ID, SURVEY_ID, FOLLOW_UP_DATE,
           COALESCE(PHQ9_SCORE, 0) AS PHQ9_SCORE,
           COALESCE(GAD7_SCORE, 0) AS GAD7_SCORE,
           COALESCE(WORK_PRODUCTIVITY_SCORE, 0) AS WORK_PRODUCTIVITY_SCORE,
           COALESCE(LIFE_SATISFACTION_SCORE, 0) AS LIFE_SATISFACTION_SCORE,
           COALESCE(NULLIF(TRIM(MEDICATION_ADHERENCE), ''''), ''Unknown'') AS MEDICATION_ADHERENCE,
           COALESCE(THERAPY_ATTENDANCE_RATE, 0) AS THERAPY_ATTENDANCE_RATE,
           COALESCE(NULLIF(TRIM(SYMPTOM_SEVERITY), ''''), ''Unknown'') AS SYMPTOM_SEVERITY,
           COALESCE(NULLIF(TRIM(RECOMMEND_TREATMENT), ''''), ''Unknown'') AS RECOMMEND_TREATMENT
    FROM MH_PERFORMANCE_TEST.MH_RAW.TREATMENTS_OUTCOMES;   -- ← Fixed


    -- 6. HARM_WORKPLACE_DETAILS
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_WORKPLACE_DETAILS;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_WORKPLACE_DETAILS AS
    SELECT COMPANY_ID,
           COALESCE(NULLIF(TRIM(COMPANY_NAME), ''''), ''Unknown'') AS COMPANY_NAME,
           COALESCE(TECH_COMPANY, FALSE) AS TECH_COMPANY,
           COALESCE(NULLIF(TRIM(EMPLOYEE_COUNT_RANGE), ''''), ''Unknown'') AS EMPLOYEE_COUNT_RANGE,
           COALESCE(REMOTE_WORK_POLICY, FALSE) AS REMOTE_WORK_POLICY,
           COALESCE(MENTAL_HEALTH_BENEFITS, FALSE) AS MENTAL_HEALTH_BENEFITS,
           COALESCE(WELLNESS_PROGRAM_AVAILABLE, FALSE) AS WELLNESS_PROGRAM_AVAILABLE,
           COALESCE(EAP_PROGRAM, FALSE) AS EAP_PROGRAM,
           COALESCE(MENTAL_HEALTH_COVERAGE_PCT, 0) AS MENTAL_HEALTH_COVERAGE_PCT,
           COALESCE(NULLIF(TRIM(SICK_LEAVE_DAYS), ''''), ''Unknown'') AS SICK_LEAVE_DAYS,
           COALESCE(FLEXIBLE_HOURS, FALSE) AS FLEXIBLE_HOURS,
           COALESCE(MENTAL_HEALTH_TRAINING, FALSE) AS MENTAL_HEALTH_TRAINING,
           COALESCE(STIGMA_REDUCTION_PROGRAMS, FALSE) AS STIGMA_REDUCTION_PROGRAMS
    FROM MH_PERFORMANCE_TEST.MH_RAW.WORKPLACE_DETAILS;   -- ← Fixed


    -- 7. HARM_SURVEY_COMPANY_MAPPINGS
    TRUNCATE TABLE IF EXISTS MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_COMPANY_MAPPINGS;
    CREATE OR REPLACE TABLE MH_PERFORMANCE_TEST.MH_HARMONIZED.HARM_SURVEY_COMPANY_MAPPINGS AS
    WITH RankedMappings AS (
        SELECT SURVEY_ID, COMPANY_ID,
               ROW_NUMBER() OVER (PARTITION BY SURVEY_ID ORDER BY COMPANY_ID) AS rn
        FROM MH_PERFORMANCE_TEST.MH_RAW.SURVEY_COMPNAY_MAPPINGS
        WHERE SURVEY_ID IS NOT NULL AND COMPANY_ID IS NOT NULL
    )
    SELECT SURVEY_ID, COMPANY_ID
    FROM RankedMappings
    WHERE rn = 1;   -- ← Fixed schema


    RETURN ''All 7 harmonized tables successfully truncated and reloaded!'';

END;
';