CREATE OR REPLACE PROCEDURE MH_PERFORMANCE_TEST.MH_RAW.LOAD_RAW_SP()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN

    -- Source Table (SYNTHETIC_LAB) -> Target Table (MH_RAW)

    -- 1. DEMOGRAPHIC_EXTENDED
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.DEMOGRAPHIC_EXTENTED;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.DEMOGRAPHIC_EXTENTED (
        EDUCATION_LEVEL,
        EMPLOYMENT_STATUS,
        HAS_CHILDREN,
        HEALTH_INSURANCE_TYPE,
        HOUSEHOLD_SIZE,
        INCOME_LEVEL,
        MARITAL_STATUS,
        SURVEY_ID,
        URBAN_RURAL,
        YEARS_IN_FIELD
    )
    SELECT 
        EDUCATION_LEVEL,
        EMPLOYMENT_STATUS,
        HAS_CHILDREN,
        HEALTH_INSURANCE_TYPE,
        HOUSEHOLD_SIZE,
        INCOME_LEVEL,
        MARITAL_STATUS,
        SURVEY_ID,
        URBAN_RURAL,
        YEARS_IN_FIELD
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_DEMOGRAPHIC_EXTENDED_1M;

    -- 2. PATIENT_HISTORY
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.PATIENT_HISTORY;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.PATIENT_HISTORY (
        CURRENT_STATUS,
        DIAGNOSIS,
        DIAGNOSIS_DATE,
        HISTORY_ID,
        IMPROVEMENT_SCORE,
        INSURANCE_COVERAGE,
        MEDICATION,
        SESSIONS_COMPLETED,
        SURVEY_ID,
        TREATMENT_DURATION_MONTHS,
        TREATMENT_TYPE
    )
    SELECT 
        CURRENT_STATUS,
        DIAGNOSIS,
        DIAGNOSIS_DATE,
        HISTORY_ID,
        IMPROVEMENT_SCORE,
        INSURANCE_COVERAGE,
        MEDICATION,
        SESSIONS_COMPLETED,
        SURVEY_ID,
        TREATMENT_DURATION_MONTHS,
        TREATMENT_TYPE
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_HISTORY_1M;

    -- 3. SURVEY_COMPNAY_MAPPINGS (using FINAL_MAPPINGS_1M)
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.SURVEY_COMPNAY_MAPPINGS;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.SURVEY_COMPNAY_MAPPINGS (
        SURVEY_ID,
        COMPANY_ID
    )
    SELECT 
        SURVEY_ID,
        COMPANY_ID 
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_MAPPINGS_1M;

    -- 4. SURVEY_AUGMENTED (using FINAL_SURVEY_1M)
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.SURVEY_AUGMENTED;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.SURVEY_AUGMENTED(
        AGE,
        ANONYMITY,
        BENEFITS,
        CARE_OPTIONS,
        COMMENTS,
        COUNTRY,
        COWORKERS,
        FAMILY_HISTORY,
        GENDER,
        LEAVE,
        MENTAL_HEALTH_CONSEQUENCE,
        MENTAL_HEALTH_INTERVIEW,
        MENTAL_VS_PHYSICAL,
        NO_EMPLOYEES,
        OBS_CONSEQUENCE,
        PHYS_HEALTH_CONSEQUENCE,
        PHYS_HEALTH_INTERVIEW,
        REMOTE_WORK,
        SEEK_HELP,
        SELF_EMPLOYED,
        STATE,
        SUPERVISOR,
        SURVEY_ID,
        TECH_COMPANY,
        TIMESTAMP,
        TREATMENT,
        WELLNESS_PROGRAM,
        WORK_INTERFERE
    )
    SELECT 
        AGE,
        ANONYMITY,
        BENEFITS,
        CARE_OPTIONS,
        COMMENTS,
        COUNTRY,
        COWORKERS,
        FAMILY_HISTORY,
        GENDER,
        LEAVE,
        MENTAL_HEALTH_CONSEQUENCE,
        MENTAL_HEALTH_INTERVIEW,
        MENTAL_VS_PHYSICAL,
        NO_EMPLOYEES,
        OBS_CONSEQUENCE,
        PHYS_HEALTH_CONSEQUENCE,
        PHYS_HEALTH_INTERVIEW,
        REMOTE_WORK,
        SEEK_HELP,
        SELF_EMPLOYED,
        STATE,
        SUPERVISOR,
        SURVEY_ID,
        TECH_COMPANY,
        TIMESTAMP,
        TREATMENT,
        WELLNESS_PROGRAM,
        WORK_INTERFERE
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_SURVEY_1M;

    -- 5. SURVEY_RESPONCE_DETAILS
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.SURVEY_RESPONCE_DETAILS;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.SURVEY_RESPONCE_DETAILS (
        ANONYMITY_CONCERN,
        BENEFITS_AWARENESS,
        LEAVE_DIFFICULTY,
        RESPONSE_COMPLETENESS,
        RESPONSE_TIME_SECONDS,
        STIGMA_PERCEPTION_SCORE,
        SUPPORT_NETWORK_SCORE,
        SURVEY_ID,
        TREATMENT_BARRIER_SCORE,
        WORK_IMPACT_SEVERITY
    )
    SELECT 
        ANONYMITY_CONCERN,
        BENEFITS_AWARENESS,
        LEAVE_DIFFICULTY,
        RESPONSE_COMPLETENESS,
        RESPONSE_TIME_SECONDS,
        STIGMA_PERCEPTION_SCORE,
        SUPPORT_NETWORK_SCORE,
        SURVEY_ID,
        TREATMENT_BARRIER_SCORE,
        WORK_IMPACT_SEVERITY
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_SURVEY_RESPONCE_DETAILS_1M;

    -- 6. TREATMENTS_OUTCOMES
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.TREATMENTS_OUTCOMES;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.TREATMENTS_OUTCOMES (
        FOLLOW_UP_DATE,
        GAD7_SCORE,
        HISTORY_ID,
        LIFE_SATISFACTION_SCORE,
        MEDICATION_ADHERENCE,
        OUTCOME_ID,
        PHQ9_SCORE,
        RECOMMEND_TREATMENT,
        SURVEY_ID,
        SYMPTOM_SEVERITY,
        THERAPY_ATTENDANCE_RATE,
        WORK_PRODUCTIVITY_SCORE
    )
    SELECT 
        FOLLOW_UP_DATE,
        GAD7_SCORE,
        HISTORY_ID,
        LIFE_SATISFACTION_SCORE,
        MEDICATION_ADHERENCE,
        OUTCOME_ID,
        PHQ9_SCORE,
        RECOMMEND_TREATMENT,
        SURVEY_ID,
        SYMPTOM_SEVERITY,
        THERAPY_ATTENDANCE_RATE,
        WORK_PRODUCTIVITY_SCORE
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_TREATMENTS_OUTCOMES_1M;

    -- 7. WORKPLACE_DETAILS (using FINAL_WORKPLACE_1M)
    TRUNCATE TABLE MH_PERFORMANCE_TEST.MH_RAW.WORKPLACE_DETAILS;
    INSERT INTO MH_PERFORMANCE_TEST.MH_RAW.WORKPLACE_DETAILS (
        COMPANY_ID,
        COMPANY_NAME,
        EAP_PROGRAM,
        EMPLOYEE_COUNT_RANGE,
        FLEXIBLE_HOURS,
        MENTAL_HEALTH_BENEFITS,
        MENTAL_HEALTH_COVERAGE_PCT,
        MENTAL_HEALTH_TRAINING,
        REMOTE_WORK_POLICY,
        SICK_LEAVE_DAYS,
        STIGMA_REDUCTION_PROGRAMS,
        TECH_COMPANY,
        WELLNESS_PROGRAM_AVAILABLE
    )
    SELECT 
        COMPANY_ID,
        COMPANY_NAME,
        EAP_PROGRAM,
        EMPLOYEE_COUNT_RANGE,
        FLEXIBLE_HOURS,
        MENTAL_HEALTH_BENEFITS,
        MENTAL_HEALTH_COVERAGE_PCT,
        MENTAL_HEALTH_TRAINING,
        REMOTE_WORK_POLICY,
        SICK_LEAVE_DAYS,
        STIGMA_REDUCTION_PROGRAMS,
        TECH_COMPANY,
        WELLNESS_PROGRAM_AVAILABLE
    FROM MH_PERFORMANCE_TEST.SYNTHETIC_LAB.FINAL_WORKPLACE_1M;

    RETURN ''Success: All tables truncated and data loaded.'';
END;';




call MH_PERFORMANCE_TEST.MH_RAW.LOAD_RAW_SP();
