CREATE OR REPLACE PROCEDURE "SP_DIMENSION_METRIC_VEIW"()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    ----------------------------------------------------------------
    -- DIMENSION METRICS VIEW
    ----------------------------------------------------------------
    CREATE OR REPLACE VIEW MH_DEV_DB.MH_CONSUMPTION.V_DIMENSION_METRICS AS
    SELECT
        ''TREATMENT_TYPE'' AS DIMENSION,
        TREATMENT_TYPE AS DIMENSION_VALUE,
        ''Treatment_Effectiveness'' AS KPI_NAME,
        ROUND(AVG(IMPROVEMENT_SCORE), 2) AS KPI_VALUE
    FROM MH_DEV_DB.MH_CONSUMPTION.V_MASTER_ANALYTICS
    GROUP BY 1, 2, 3

    UNION ALL
    
    SELECT
        ''INCOME_LEVEL'' AS DIMENSION,
        COALESCE(NULLIF(INCOME_LEVEL, ''''), ''UNKNOWN'') AS DIMENSION_VALUE,
        ''Treatment Prevalence'' AS KPI_NAME,
        ROUND(
            100.0 * COUNT(CASE WHEN UPPER(TRIM(IS_TREATED)) = ''TRUE'' THEN 1 END)
            / NULLIF(COUNT(*), 0),
            2
        ) AS KPI_VALUE
    FROM MH_DEV_DB.MH_CONSUMPTION.V_MASTER_ANALYTICS
    GROUP BY 1, 2, 3

    UNION ALL

    SELECT
        ''EDUCATION_LEVEL'' AS DIMENSION,
        EDUCATION_LEVEL AS DIMENSION_VALUE,
        ''TREATMENT_COMPLETION_PCT'' AS KPI_NAME,
        ROUND(
            100.0 * COUNT_IF(UPPER(TRIM(TREATMENT_STATUS)) = ''COMPLETED'')
            / NULLIF(COUNT(*), 0),
            2
        ) AS KPI_VALUE
    FROM MH_DEV_DB.MH_CONSUMPTION.V_MASTER_ANALYTICS
    GROUP BY 1, 2, 3

    UNION ALL

    SELECT
        ''WORK_INTERFERENCE'' AS DIMENSION,
        WORK_INTERFERE AS DIMENSION_VALUE,
        ''PERCENTAGE'' AS KPI_NAME,
        ROUND(
            (COUNT(*) * 100.0)
            / NULLIF((SELECT COUNT(*) FROM MH_DEV_DB.MH_CONSUMPTION.V_MASTER_ANALYTICS), 0),
            2
        ) AS KPI_VALUE
    FROM MH_DEV_DB.MH_CONSUMPTION.V_MASTER_ANALYTICS
    GROUP BY 1, 2, 3;

    RETURN ''SP_DIMENSION_METRIC_VEIW completed successfully'';
END;
';


call MH_DEV_DB.MH_CONSUMPTION.SP_DIMENSION_METRIC_VEIW();



GRANT OWNERSHIP
  ON VIEW V_DIMENSION_METRICS
  TO ROLE MH_DATA_ENGINEER_RW
  REVOKE CURRENT GRANTS;