USE ROLE ACCOUNTADMIN;

-- Create Resource Monitor for ELT Warehouse
CREATE OR REPLACE RESOURCE MONITOR MH_ELT_RM
WITH
  CREDIT_QUOTA = 100
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS 
    ON 70 PERCENT DO NOTIFY
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Create Resource Monitor for Analyst Warehouse
CREATE OR REPLACE RESOURCE MONITOR MH_ANALYST_RM
WITH
  CREDIT_QUOTA = 100
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS 
    ON 70 PERCENT DO NOTIFY
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- Assign Resource Monitors to Warehouses
ALTER WAREHOUSE MH_ELT_WH SET RESOURCE_MONITOR = MH_ELT_RM;
ALTER WAREHOUSE MH_ANALYST_WH SET RESOURCE_MONITOR = MH_ANALYST_RM;

-- Grant Resource Monitor Privileges to SYSADMIN
GRANT MODIFY, MONITOR ON RESOURCE MONITOR MH_ELT_RM TO ROLE SYSADMIN;
GRANT MODIFY, MONITOR ON RESOURCE MONITOR MH_ANALYST_RM TO ROLE SYSADMIN;